language: android
jdk:
  - openjdk7
#  - openjdk8
#  - oraclejdk7
sudo: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
#    - sys-img-x86-android-17

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew test
  - ./gradlew connectedAndroidTest

deploy:
  provider: releases
  api_key:
    secure: y7UjJO2yEmySKTKJUgrYQhtjsDOSbgZ7xl4mrkLmNZWUHIDyYxuC22dJa2XUCrP0/t/Yh5RmsEjCbSv+k/Y/OMVEEpEWgOv6E5PSuHiQHzAG/5rqlauMQFJ1JSfGwEl4cqDBS07vLWeiSbOmscDVLNPw+I2hBwQ6pap31wVEPy5OrQqYrOgEcj9dm4jV3dlgXpwQw5Ruwq4lJYLorNTW4IR/KEgTSepMcyDrrElUntC/zsyMGpUAAVEP12PTGTyoHRTgNxnA/OMLj6sSt61KDJ/TRjVJ9R8afFGESFVEmOwWda915OtjiSr71/AMo7eOUdgIuADirTaGDgsvw6+A8AkzaCRcS8n4WeU7WKIKy1Lg757suaJexS8dmw7n1aJFbSXlobtDDuLWdF0HX+Le7dEKePvinGuZrm95xnpbaDERxLit9kiUCcZqbcVjQMl2VySiPS4j4iCXcgDkZBXxPn+Nksane6HOmbB9MMv4D8IHiOkyaerDc3DF+SOFfHZiPu5x+uU5TfIT6HFFKqDrMk2w2sg9alZrEyzjfPh1nBZyIIpW7vQAbqY7288uaPQL6s1m/HD7SGT0mOqpIZ+u/OiuQOJbcpHzt9YouPeSm/UK6zoGT/YkXUvAv5ClL/XpdC9zxaWpw9fAbKmzutEAxAnTu1SlVHV/QLtopjXh4X4=
  file: arnotes/test_deploy.txt
  on:
    repo: Arnotjevleesch/Arnotes
