language: android
jdk:
  - openjdk7
#  - openjdk8
#  - oraclejdk7
sudo: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
#    - sys-img-x86-android-17

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
#  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
  #- android list target
  #- ./gradlew test
  #- ./gradlew connectedAndroidTest

deploy:
  provider: releases
  file: test_deploy2.txt
  on:
    repo: Arnotjevleesch/Arnotes
    branch: master
  api-key:
    secure: nxFroRqQGSWyoZofNTDslJNUF5l+2vNL8JqO9XeuIpudh3gSDNknpdExl7y7HXgj3MSWfUE28l0CzcszDPM1ukfohiMS6A91yJgVUqX2Pr0xFJc4fTdKZ1yZIKTPIXmHj9fR/SUHC//T0m+COzTyQuzGI05j6D8iNkDV7ecGhu3PsA2m9/C3TKIs/HnBPINRh9jtFv4pCrGJuOSfblMKsEbygF6GRMz7oe1qnUr0Sn49dCfvLTup4hpKQ+rW6g6oemUEXlm62fscRz3wH6a3t+oXy1+F90wQIJLDU8uJDKnRu6bs/qvrRaDwwqWK9S367Oh1ZI8G0SlqY2QZqihS7JfNESYTnnnGj0bmuiTAnos5XPM69GlqLbtLVH6BrchO0mNdpkVeBRzMP4VbhX9Kg/oAJ/MmI6ei197oZrpqMzeamNYUW99PFbNl95TFI/mH4jcEFmYDxtULzkeDD8TFyxQsvs4YlwBDZ+kmTh2qNyzekmGmrfQJs4HDDG3WRkzOCElDkKfZVAVFN45e1od8wIHFojmazxyl+ynUa/z1DIAz0gr+aiFhKtyCMZ4DXQZjf+dt51RI6Gh25cvQQ0ofTit8r1ARChynSmIFYfM2Iy/4wOP5rXt6qPdZeE/C3chR+vV4fDHC4p3RzKAovkSuIK/qDYD3txvdJX40p04InL4=
