language: android
jdk:
- openjdk7
sudo: false
android:
  components:
  - build-tools-22.0.1
  - android-22
  - sys-img-armeabi-v7a-android-22
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
before_script: 
script: 
deploy:
  provider: releases
  user: Arnotjevleesch
  password:
      secure: EektyMLXRW54xy9348Epo+JAAXMb4x5w8fqXNfMy7UboKzkUNd78GfJQUTk67HtJLud3oo3wr8y6/6oM8gLYamQsV/LKi9QF03mM8dlfmEqL0qxeQ2K+63D8xT+NF3onzB/arzbEzz3vYa/jMFrA/yLxXo36u+IX3jAQsuDweDBFjHXXhxsFlQDjxwHpQed/DHrqgHmQUIwaqQoDzvkiE/cLGqCvuVW80o+V5Lh/bqZh1o5jQsDX33KZ2YWfCV5/AckeFp/L+1k5vM/4bo4F4iAv757DxCmPaZJvgqIH9DGJVem84zHHzvlRyLkilkBQKEhgoPhuQjOEV1PO2IG/c9GLuwxNPm3IXyAUQHm9d5PGq8AgoXvc1oaWOXG6SHscZp4Adyrt+BGgCYBoLjSmwXGiAVfNAprqZXw2714ZGSkokHnbua4+o1zNqAqcAi55OHpeEE65EHwcYLFwrwE0EOp7cAWeSHU0CGN4Gj0wvxQfoLopuGkB78t70yXykKB/wiTfaL9HiouFJOutUAmb2QmoNMX0CLuUQD7v/zA5VElmO0m/XmQTpnTa8fze4mEoP5RBVmX019yzWDE0O+fPM/+c6bAl49sgb0qSq72O3rCWF5ah7Dbk1UTC0e5V9yLc2q1Ah6AwO+cREv7JA8Ng92riy/J+r7OM589olQiGyV0=
  file: test_deploy2.txt
  skip_cleanup: true
  on:
    repo: Arnotjevleesch/Arnotes
    branch: master
